version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: doze_check_mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_INIT}
    volumes:
      - doze_check_mongo_data:/data/db

volumes:
  doze_check_mongo_data:
